import type { TelecomProduct } from "@/core/types/api.types";

export const fallbackProducts: TelecomProduct[] = [
  {
    id: "router-5g-pro",
    sku: "FABU-5G-RTR-PRO",
    name: "Router 5G Pro",
    category: "Router",
    brand: "Fabu",
    description: "Router Wi-Fi 6 cho gia đình và cửa hàng nhỏ, tối ưu dùng kèm gói data tháng.",
    price: 1890000,
    originalPrice: 2190000,
    stockQuantity: 42,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "sim-data-120",
    sku: "SIM-DATA-120GB",
    name: "SIM Data 120GB",
    category: "SIM",
    brand: "Fabu",
    description: "SIM data tốc độ cao cho khách hàng cần kết nối ổn định theo tháng.",
    price: 250000,
    originalPrice: 290000,
    stockQuantity: 168,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "mesh-mini",
    sku: "FABU-MESH-MINI",
    name: "Mesh Wi-Fi Mini",
    category: "Accessory",
    brand: "Fabu",
    description: "Mở rộng vùng phủ sóng cho nhà nhiều tầng hoặc văn phòng nhỏ.",
    price: 690000,
    originalPrice: 790000,
    stockQuantity: 57,
    isFeatured: false,
    isActive: true,
  },
  {
    id: "cpe-outdoor",
    sku: "FABU-CPE-OUTDOOR",
    name: "Outdoor CPE 5G",
    category: "Enterprise",
    brand: "Fabu",
    description: "Thiết bị CPE ngoài trời cho điểm bán, kho và khu vực sóng yếu.",
    price: 3290000,
    originalPrice: 3590000,
    stockQuantity: 18,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "power-bank",
    sku: "FABU-PB-20K",
    name: "Pin dự phòng 20.000mAh",
    category: "Accessory",
    brand: "Fabu",
    description: "Phụ kiện cross-sell phù hợp với khách mua thiết bị di động.",
    price: 420000,
    originalPrice: 490000,
    stockQuantity: 84,
    isFeatured: false,
    isActive: true,
  },
  {
    id: "business-kit",
    sku: "FABU-BIZ-KIT",
    name: "Business Connectivity Kit",
    category: "Enterprise",
    brand: "Fabu",
    description: "Combo router, SIM data và hỗ trợ triển khai cho cửa hàng.",
    price: 4490000,
    originalPrice: 4990000,
    stockQuantity: 12,
    isFeatured: true,
    isActive: true,
  },
];
